#include<cstdio> 
#include<iostream> 
#include<cmath> 
#include<cstring> 
#include<cstdlib> 
#include<vector> 
#include<queue> 
#include<list> 
#include<stack> 
#include<set> 
#include<map> 
#include<string> 
#include<algorithm> 
#include<functional> 
#include<bitset> 
#include<ctime> 
#include<stdio.h> 
#include<time.h> 
#include<windows.h>
#include<conio.h>
#include<io.h>
#include<process.h>